import yfinance as yf
import pandas as pd
import numpy as np

def fetch_and_preprocess_data(ticker="SPY", start_date="2015-01-01", end_date="2025-01-01"):
    """
    Fetches historical stock data and calculates technical indicators for RL state space.
    """
    print(f"Fetching data for {ticker} from {start_date} to {end_date}...")
    
    # 1. Data Sourcing
    df = yf.download(ticker, start=start_date, end=end_date)
    
    # Flatten multi-index columns if yfinance returns them
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
        
    # --- NEW VIX SOURCING ---
    vix_df = yf.download("^VIX", start=start_date, end=end_date)
    if isinstance(vix_df.columns, pd.MultiIndex):
        vix_df.columns = vix_df.columns.get_level_values(0)
        
    # Add the VIX Close price as a new column in our main dataframe
    df['VIX'] = vix_df['Close']
    # ------------------------
        
    # 2. Data Cleaning
    df.ffill(inplace=True)
    df.bfill(inplace=True)
    
    # 3. Feature Engineering (Technical Indicators)
    
    # -- Bollinger Bands (20-day SMA, 2 Standard Deviations) --
    df['SMA_20'] = df['Close'].rolling(window=20).mean()
    df['StdDev_20'] = df['Close'].rolling(window=20).std()
    df['BB_Upper'] = df['SMA_20'] + (df['StdDev_20'] * 2)
    df['BB_Lower'] = df['SMA_20'] - (df['StdDev_20'] * 2)
    
    # -- MACD (12-day EMA - 26-day EMA) --
    df['EMA_12'] = df['Close'].ewm(span=12, adjust=False).mean()
    df['EMA_26'] = df['Close'].ewm(span=26, adjust=False).mean()
    df['MACD'] = df['EMA_12'] - df['EMA_26']
    df['MACD_Signal'] = df['MACD'].ewm(span=9, adjust=False).mean()
    
    # -- RSI (14-day) --
    delta = df['Close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
    
    # Calculate RS and handle division by zero
    rs = gain / loss
    df['RSI'] = np.where(loss == 0, 100, 100 - (100 / (1 + rs)))
    
    # Drop NaN values generated by rolling windows (the first 26 days)
    df.dropna(inplace=True)
    
    print(f"Data preprocessing complete. Final dataset shape: {df.shape}")
    return df

# Execute the function
if __name__ == "__main__":
    market_data = fetch_and_preprocess_data()
    print(market_data[['Close', 'MACD', 'RSI', 'BB_Upper', 'BB_Lower']].tail())